# Generated by Django 4.2.17 on 2025-01-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='core.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoGerencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerencias', to='core.gerencia')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_gerente', to='core.datospersonal')),
            ],
        ),
        migrations.AddField(
            model_name='datospersonal',
            name='gerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_gerencia', to='core.gerencia'),
        ),
        migrations.AddField(
            model_name='datospersonal',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisados', to='core.datospersonal'),
        ),
        migrations.AddField(
            model_name='datospersonal',
            name='tipo_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='core.tipopersonal'),
        ),
        migrations.AddField(
            model_name='datospersonal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_personal', to=settings.AUTH_USER_MODEL),
        ),
    ]
