# Generated by Django 4.2.17 on 2025-01-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datospersonal_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonal',
            name='fecha_ingreso',
            field=models.DateField(default='2023-11-01'),
            preserve_default=False,
        ),
    ]
