# Generated by Django 4.2.17 on 2025-02-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datospersonal_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='nivel',
        ),
    ]
