# Generated by Django 4.2.17 on 2025-02-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0027_alter_formacion_options'),
        ('core', '0004_remove_cargo_nivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ('-activo', '-fecha_inicio')},
        ),
        migrations.AddField(
            model_name='datospersonal',
            name='escalafon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.nivelescalafon'),
        ),
    ]
