# Generated by Django 4.2.17 on 2025-03-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_periodo_options_datospersonal_escalafon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospersonal',
            options={'ordering': ('ficha',)},
        ),
    ]
