# Generated by Django 4.2.17 on 2025-01-09 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('E', 'EMPEZADA'), ('S', 'REVISIÓN POR SUPERVISOR'), ('G', 'ENVIADO A LA GERENCIA'), ('H', 'ENVIADO A GESTIÓN HUMANA'), ('A', 'APROBADA')], default='P', max_length=1)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.datospersonal')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='core.tipopersonal')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('peso', models.SmallIntegerField()),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('E', 'EMPEZADA'), ('S', 'REVISIÓN POR SUPERVISOR'), ('G', 'ENVIADO A LA GERENCIA'), ('H', 'ENVIADO A GESTIÓN HUMANA'), ('A', 'APROBADA')], default='P', max_length=1)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='evaluacion.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('peso', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('peso', models.SmallIntegerField()),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='evaluacion.instrumento')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_empleado', models.CharField(blank=True, max_length=200, null=True)),
                ('comentario_supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('comentario_gghh', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta_empleado', models.SmallIntegerField()),
                ('respuesta_supervisor', models.SmallIntegerField(blank=True, null=True)),
                ('respuesta_definitiva', models.SmallIntegerField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.evaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluacion.seccion'),
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=200)),
                ('valor', models.SmallIntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluacion.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='LogrosYMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('porc_cumplimiento', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('anadido_por', models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.CharField(choices=[('A', 'ACTUAL'), ('P', 'PRÓXIMO')], max_length=1)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_y_metas', to='evaluacion.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidad_formacion', models.CharField(max_length=200)),
                ('prioridad', models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1)),
                ('anadido_por', models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='evaluacion.clasificacionformacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones', to='evaluacion.evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluacion.formulario'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.periodo'),
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], max_length=1)),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='core.tipopersonal')),
            ],
        ),
    ]
