# Generated by Django 4.2.17 on 2025-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='competencias',
            field=models.ManyToManyField(related_name='formaciones', to='evaluacion.competencias'),
        ),
    ]
