# Generated by Django 4.2.17 on 2025-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_formacion_competencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
