# Generated by Django 4.2.17 on 2025-01-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_evaluacion_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='estado',
        ),
    ]
