# Generated by Django 4.2.17 on 2025-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_resultadoinstrumento_opciones_tip_resultadoseccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='tip',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
