# Generated by Django 4.2.17 on 2025-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_alter_pregunta_pregunta_alter_pregunta_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
