# Generated by Django 4.2.17 on 2025-01-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_alter_seccion_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='opciones',
            name='pregunta',
            field=models.ManyToManyField(related_name='opciones', to='evaluacion.pregunta'),
        ),
    ]
