# Generated by Django 4.2.17 on 2025-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_remove_opciones_pregunta_opciones_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='calculo',
            field=models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], default='S', max_length=1),
        ),
    ]
