# Generated by Django 4.2.17 on 2025-01-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_instrumento_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='calculo',
            field=models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], default='S', max_length=1),
        ),
    ]
