# Generated by Django 4.2.17 on 2025-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0011_seccion_calculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoinstrumento',
            name='resultado_empleado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
