# Generated by Django 4.2.17 on 2025-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0012_alter_resultadoinstrumento_resultado_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoinstrumento',
            name='resultado_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoinstrumento',
            name='resultado_supervisor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoseccion',
            name='resultado_empleado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoseccion',
            name='resultado_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoseccion',
            name='resultado_supervisor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
