# Generated by Django 4.2.17 on 2025-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0013_alter_resultadoinstrumento_resultado_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='opcion',
            field=models.CharField(max_length=250),
        ),
    ]
