# Generated by Django 4.2.17 on 2025-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0016_alter_opciones_options_logrosymetas_nivel_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrosymetas',
            name='nivel_prioridad',
            field=models.CharField(blank=True, choices=[('P', 'PRIORITARIO'), ('N', 'NO PRIORITARIO')], max_length=1, null=True),
        ),
    ]
