# Generated by Django 4.2.17 on 2025-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0017_alter_logrosymetas_nivel_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='comentario_evaluado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('E', 'EMPEZADA'), ('S', 'REVISIÓN POR SUPERVISOR'), ('G', 'ENVIADO A LA GERENCIA'), ('H', 'ENVIADO A GESTIÓN HUMANA'), ('A', 'APROBADA'), ('R', 'RECHAZADA')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='prioridad',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
