# Generated by Django 4.2.17 on 2025-01-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0018_evaluacion_comentario_evaluado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='comentario_gghh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='comentario_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
