# Generated by Django 4.2.17 on 2025-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0019_evaluacion_comentario_gghh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ('periodo', 'fecha_inicio')},
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
