# Generated by Django 4.2.17 on 2025-01-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datospersonal_fecha_ingreso'),
        ('evaluacion', '0020_alter_evaluacion_options_alter_pregunta_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=80)),
                ('valor_requerido', models.IntegerField()),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalafones', to='core.tipopersonal')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEscalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_por', models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], max_length=1)),
                ('escalafon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalafones', to='evaluacion.escalafon')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalafones', to='evaluacion.evaluacion')),
            ],
        ),
    ]
