# Generated by Django 4.2.17 on 2025-02-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0021_escalafon_resultadoescalafon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='fecha_aprobacion',
            new_name='fecha_entrega',
        ),
    ]
