# Generated by Django 4.2.17 on 2025-02-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0022_rename_fecha_aprobacion_evaluacion_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='calculo_escalafon',
            field=models.CharField(blank=True, choices=[('S', 'SUMA'), ('P', 'PROMEDIO'), ('M', 'MÍNIMO')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='escalafon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluacion.escalafon'),
        ),
    ]
