# Generated by Django 4.2.17 on 2025-02-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0023_instrumento_calculo_escalafon_instrumento_escalafon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalafon',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='escalafon',
            name='valor_requerido',
        ),
        migrations.CreateModel(
            name='NivelEscalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=80)),
                ('valor_requerido', models.IntegerField()),
                ('escalafon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.escalafon')),
            ],
        ),
    ]
