# Generated by Django 4.2.17 on 2025-02-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0024_remove_escalafon_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalafon',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
