# Generated by Django 4.2.17 on 2025-02-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0026_alter_nivelescalafon_escalafon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formacion',
            options={'ordering': ['prioridad']},
        ),
    ]
