# Generated by Django 4.2.17 on 2025-03-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0028_aspectopromocion_detalleaspectopromocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleaspectopromocion',
            name='formulario_promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_aspectos', to='evaluacion.formulariopromocion'),
        ),
        migrations.AlterField(
            model_name='detalleaspectopromocion',
            name='pregunta_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_aspectos', to='evaluacion.pregunta'),
        ),
    ]
