# Generated by Django 4.2.17 on 2025-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0029_alter_detalleaspectopromocion_formulario_promocion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestasolicitudpromocion',
            name='comentario_gghh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='prioridad',
            field=models.CharField(choices=[(1, '1 - Asociado a Competencias Técnicas'), (2, '2 - Asociado a Competencias Genéricas'), (3, '3 - Otras')], max_length=1),
        ),
        migrations.AlterField(
            model_name='respuestasolicitudpromocion',
            name='justificacion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
