# Generated by Django 4.2.17 on 2025-03-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0030_respuestasolicitudpromocion_comentario_gghh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestasolicitudpromocion',
            name='respuesta_asociada',
        ),
    ]
