# Generated by Django 4.2.17 on 2025-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0031_remove_respuestasolicitudpromocion_respuesta_asociada'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectopromocion',
            name='antiguedad',
            field=models.BooleanField(default=False),
        ),
    ]
