# Generated by Django 4.2.17 on 2025-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0033_solicitudpromocion_comentario_general_gghh'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestasolicitudpromocion',
            name='enviada_por',
            field=models.CharField(choices=[('E', 'EMPLEADO'), ('S', 'SUPERVISOR'), ('G', 'GERENTE'), ('H', 'GESTION HUMANA')], default='S', max_length=1),
        ),
    ]
