# Generated by Django 4.2.17 on 2025-03-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0034_respuestasolicitudpromocion_enviada_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestasolicitudpromocion',
            name='comentario_gghh',
        ),
    ]
