# Generated by Django 4.2.17 on 2025-03-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0035_remove_respuestasolicitudpromocion_comentario_gghh'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpromocion',
            name='formulario_promocion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.formulariopromocion'),
            preserve_default=False,
        ),
    ]
